services:
  - type: web
    name: djangoapp
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
    startCommand: gunicorn GestionDeTaches.wsgi:application
    
